---
bibliography: "inst/REFERENCES.bib"
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# arkhaia: Archaeological and Historical Analysis

<!-- badges: start -->
<!-- badges: end -->

The R package `arkhaia` contains functions related to research on economic relationships via archaeological or otherwise historical data. The main focus is on evaluation of changes in long-term "integrating" or "integrated" relationships over time between communities, primarily through the material evidence of artifact assemblages. The problem of how to detect similar patterns over time  in a given behavior is a broad one that requires specificity in order to address mathematically, and so this package provides the tools necessary for handling counts of artifacts, as well as measurement data (such as prices).

The package relies on `Rcpp` and `RcppArmadillo` [@eddelbuettel_rcpparmadillo_2014;@eddelbuettel_extending_2018].


## Installation

To obtain the development version of the package, `devtools` can be used to install `arkhaia` from GitHub:

``` r
library(devtools)
install_github("scollinselliott/arkhaia", dependencies = TRUE, build_vignettes = TRUE) 
```

## Methods

### Homogeneity via Effect Size

Establishing a measure of practical signficance for the comparison of finds assemblages in their depositional contexts. Whether or not a context is "representative" of another is assessed on the basis of the homogeneity of the distribution of finds. The relevant paper has been reviewed and is under revision: @collins-elliott_evaluating_nodate, "Evaluating..."

* Cressie-Read power-divergence statistic to estimate $\chi^2$ [@cressie_multinomial_1984;@read_goodnessfit_1988]
* Bergsma's bias-corrected Cramér's $V$ [@bergsma_bias-correction_2013]
* Effect size as a measure of homogeneity between "related" and "unrelated" archaeological contexts, evaluated on the basis of count data and presence/absence data.
* Leave-one-out (LOO) validation of effect sizes.
* Inference based on sign error and practical signficance.

### Random Right-Censored Count Data

Random right-censoring of archaeological count data. Assemblages of artifacts that do _not_ belong to primary contexts (i.e., "random" secondary or tertiary contexts), comprise a minimum amount of finds that were "is use" in a given locality. From a contingency table of those minimum counts, it is possible to generate distributions of counts in use from which to evaluate This paper is currently under review: @collins-elliott_random_nodate, "Random..."

* Estimating the rate of a Poisson distribution based on a contingency table of minimum counts.
* Resampling routines to generate contingency tables accoriding to a truncated Poisson distribution, representing counts "in use" as opposed to those deposied.

### Least Squares Sepctral Analysis 

Least squares spectral analysis (LSSA), with an implementation of fitting by lowest frequency iteratively (LSSA-LFI), to fit sparse time-indexed observations and then evaluate whether there exists linear dependence in their data-generating process via model comparison. The paper applying this method to Babylonian price data is under review: @collins-elliott_revisiting_nodate, "Revisiting..."

## References