// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// LSSA_arma
arma::mat LSSA_arma(const arma::mat& dat, const arma::colvec& freq, int intercept);
RcppExport SEXP _arkhaia_LSSA_arma(SEXP datSEXP, SEXP freqSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< int >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(LSSA_arma(dat, freq, intercept));
    return rcpp_result_gen;
END_RCPP
}
// LSSA_resid_arma
arma::vec LSSA_resid_arma(const arma::mat& dat, double freq, int intercept);
RcppExport SEXP _arkhaia_LSSA_resid_arma(SEXP datSEXP, SEXP freqSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< double >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< int >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(LSSA_resid_arma(dat, freq, intercept));
    return rcpp_result_gen;
END_RCPP
}
// LSSA_LFI_arma
arma::mat LSSA_LFI_arma(const arma::mat& x, int n_iter, int intercept);
RcppExport SEXP _arkhaia_LSSA_LFI_arma(SEXP xSEXP, SEXP n_iterSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(LSSA_LFI_arma(x, n_iter, intercept));
    return rcpp_result_gen;
END_RCPP
}
// LSSA_LFI_model_arma
arma::mat LSSA_LFI_model_arma(const arma::mat& x, arma::vec t_, int n_iter, int intercept);
RcppExport SEXP _arkhaia_LSSA_LFI_model_arma(SEXP xSEXP, SEXP t_SEXP, SEXP n_iterSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t_(t_SEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(LSSA_LFI_model_arma(x, t_, n_iter, intercept));
    return rcpp_result_gen;
END_RCPP
}
// partition_list_to_matrix_arma
arma::mat partition_list_to_matrix_arma(Rcpp::List x);
RcppExport SEXP _arkhaia_partition_list_to_matrix_arma(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(partition_list_to_matrix_arma(x));
    return rcpp_result_gen;
END_RCPP
}
// LSSA_LFI_candidates_arma
int LSSA_LFI_candidates_arma(arma::mat& x, arma::vec& start_idx, arma::vec& x_rows, arma::mat& sets, int n_iter, int intercept);
RcppExport SEXP _arkhaia_LSSA_LFI_candidates_arma(SEXP xSEXP, SEXP start_idxSEXP, SEXP x_rowsSEXP, SEXP setsSEXP, SEXP n_iterSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type start_idx(start_idxSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x_rows(x_rowsSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type sets(setsSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(LSSA_LFI_candidates_arma(x, start_idx, x_rows, sets, n_iter, intercept));
    return rcpp_result_gen;
END_RCPP
}
// LSSA_LFI_multi_arma
arma::mat LSSA_LFI_multi_arma(arma::mat& x, arma::vec& start_idx, arma::vec& x_rows, int n_iter, int intercept);
RcppExport SEXP _arkhaia_LSSA_LFI_multi_arma(SEXP xSEXP, SEXP start_idxSEXP, SEXP x_rowsSEXP, SEXP n_iterSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type start_idx(start_idxSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x_rows(x_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(LSSA_LFI_multi_arma(x, start_idx, x_rows, n_iter, intercept));
    return rcpp_result_gen;
END_RCPP
}
// lambda_col_arma
arma::vec lambda_col_arma(const arma::mat& dat, arma::vec& lambda_grid, int omit_zero);
RcppExport SEXP _arkhaia_lambda_col_arma(SEXP datSEXP, SEXP lambda_gridSEXP, SEXP omit_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type lambda_grid(lambda_gridSEXP);
    Rcpp::traits::input_parameter< int >::type omit_zero(omit_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_col_arma(dat, lambda_grid, omit_zero));
    return rcpp_result_gen;
END_RCPP
}
// trunc_pois_mat_arma
arma::mat trunc_pois_mat_arma(const arma::mat& dat, arma::vec& lambda_grid, int omit_zero);
RcppExport SEXP _arkhaia_trunc_pois_mat_arma(SEXP datSEXP, SEXP lambda_gridSEXP, SEXP omit_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type lambda_grid(lambda_gridSEXP);
    Rcpp::traits::input_parameter< int >::type omit_zero(omit_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(trunc_pois_mat_arma(dat, lambda_grid, omit_zero));
    return rcpp_result_gen;
END_RCPP
}
// CR_arma
double CR_arma(const arma::mat& X, double lambda);
RcppExport SEXP _arkhaia_CR_arma(SEXP XSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(CR_arma(X, lambda));
    return rcpp_result_gen;
END_RCPP
}
// VB_arma
double VB_arma(const arma::mat& X, double lambda);
RcppExport SEXP _arkhaia_VB_arma(SEXP XSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(VB_arma(X, lambda));
    return rcpp_result_gen;
END_RCPP
}
// MC_pois_arma
Rcpp::NumericVector MC_pois_arma(const arma::mat& X, double lambda, arma::vec& lambda_grid, int omit_zero, int M);
RcppExport SEXP _arkhaia_MC_pois_arma(SEXP XSEXP, SEXP lambdaSEXP, SEXP lambda_gridSEXP, SEXP omit_zeroSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type lambda_grid(lambda_gridSEXP);
    Rcpp::traits::input_parameter< int >::type omit_zero(omit_zeroSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(MC_pois_arma(X, lambda, lambda_grid, omit_zero, M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_arkhaia_LSSA_arma", (DL_FUNC) &_arkhaia_LSSA_arma, 3},
    {"_arkhaia_LSSA_resid_arma", (DL_FUNC) &_arkhaia_LSSA_resid_arma, 3},
    {"_arkhaia_LSSA_LFI_arma", (DL_FUNC) &_arkhaia_LSSA_LFI_arma, 3},
    {"_arkhaia_LSSA_LFI_model_arma", (DL_FUNC) &_arkhaia_LSSA_LFI_model_arma, 4},
    {"_arkhaia_partition_list_to_matrix_arma", (DL_FUNC) &_arkhaia_partition_list_to_matrix_arma, 1},
    {"_arkhaia_LSSA_LFI_candidates_arma", (DL_FUNC) &_arkhaia_LSSA_LFI_candidates_arma, 6},
    {"_arkhaia_LSSA_LFI_multi_arma", (DL_FUNC) &_arkhaia_LSSA_LFI_multi_arma, 5},
    {"_arkhaia_lambda_col_arma", (DL_FUNC) &_arkhaia_lambda_col_arma, 3},
    {"_arkhaia_trunc_pois_mat_arma", (DL_FUNC) &_arkhaia_trunc_pois_mat_arma, 3},
    {"_arkhaia_CR_arma", (DL_FUNC) &_arkhaia_CR_arma, 2},
    {"_arkhaia_VB_arma", (DL_FUNC) &_arkhaia_VB_arma, 2},
    {"_arkhaia_MC_pois_arma", (DL_FUNC) &_arkhaia_MC_pois_arma, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_arkhaia(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
