# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib arkhaia
#' @importFrom Rcpp sourceCpp
LSSA_arma <- function(dat, freq, intercept) {
    .Call('_arkhaia_LSSA_arma', PACKAGE = 'arkhaia', dat, freq, intercept)
}

#' @useDynLib arkhaia
#' @importFrom Rcpp sourceCpp
LSSA_resid_arma <- function(dat, freq, intercept) {
    .Call('_arkhaia_LSSA_resid_arma', PACKAGE = 'arkhaia', dat, freq, intercept)
}

