# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib arkhaia
#' @importFrom Rcpp sourceCpp
LSSA_arma <- function(dat, freq, intercept) {
    .Call('_arkhaia_LSSA_arma', PACKAGE = 'arkhaia', dat, freq, intercept)
}

#' @useDynLib arkhaia
#' @importFrom Rcpp sourceCpp
LSSA_resid_arma <- function(dat, freq, intercept) {
    .Call('_arkhaia_LSSA_resid_arma', PACKAGE = 'arkhaia', dat, freq, intercept)
}

#' @useDynLib arkhaia
#' @importFrom Rcpp sourceCpp
LSSA_LFI_arma <- function(x, n_iter, intercept) {
    .Call('_arkhaia_LSSA_LFI_arma', PACKAGE = 'arkhaia', x, n_iter, intercept)
}

#' @useDynLib arkhaia
#' @importFrom Rcpp sourceCpp
LSSA_LFI_model_arma <- function(x, t_, n_iter, intercept) {
    .Call('_arkhaia_LSSA_LFI_model_arma', PACKAGE = 'arkhaia', x, t_, n_iter, intercept)
}

#' @useDynLib arkhaia
#' @importFrom Rcpp sourceCpp
partition_list_to_matrix_arma <- function(x) {
    .Call('_arkhaia_partition_list_to_matrix_arma', PACKAGE = 'arkhaia', x)
}

#' @useDynLib arkhaia
#' @importFrom Rcpp sourceCpp
LSSA_LFI_candidates_arma <- function(x, start_idx, x_rows, sets, n_iter, intercept) {
    .Call('_arkhaia_LSSA_LFI_candidates_arma', PACKAGE = 'arkhaia', x, start_idx, x_rows, sets, n_iter, intercept)
}

#' @useDynLib arkhaia
#' @importFrom Rcpp sourceCpp
lambda_col_arma <- function(dat, lambda_grid, omit_zero) {
    .Call('_arkhaia_lambda_col_arma', PACKAGE = 'arkhaia', dat, lambda_grid, omit_zero)
}

#' @useDynLib arkhaia
#' @importFrom Rcpp sourceCpp
trunc_pois_mat_arma <- function(dat, lambda_grid, omit_zero) {
    .Call('_arkhaia_trunc_pois_mat_arma', PACKAGE = 'arkhaia', dat, lambda_grid, omit_zero)
}

#' @useDynLib arkhaia
#' @importFrom Rcpp sourceCpp
CR_arma <- function(X, lambda) {
    .Call('_arkhaia_CR_arma', PACKAGE = 'arkhaia', X, lambda)
}

#' @useDynLib arkhaia
#' @importFrom Rcpp sourceCpp
VB_arma <- function(X, lambda) {
    .Call('_arkhaia_VB_arma', PACKAGE = 'arkhaia', X, lambda)
}

#' @useDynLib arkhaia
#' @importFrom Rcpp sourceCpp
MC_pois_arma <- function(X, lambda, lambda_grid, omit_zero, M) {
    .Call('_arkhaia_MC_pois_arma', PACKAGE = 'arkhaia', X, lambda, lambda_grid, omit_zero, M)
}

